### ISSUE TITLE
Retire cargo-nightly-bin?

### ISSUE THREAD

**Issue by SimonSapin** [michaelsproul/rust-nightly-archlinux#11]
Is there any point in the cargo-nightly-bin package now that the Rust installer (and so the rust-nightly-bin package) includes Cargo?

http://www.reddit.com/r/rust/comments/2r92yw/psa_rust_installers_now_come_with_cargo_and_docs/

```
$ pacman -Ql rust-nightly-bin|grep cargo
rust-nightly-bin /usr/local/bin/cargo
rust-nightly-bin /usr/local/etc/bash_completion.d/cargo
rust-nightly-bin /usr/local/lib/rustlib/manifest-cargo
rust-nightly-bin /usr/local/man/man1/cargo.1.gz
rust-nightly-bin /usr/local/share/doc/cargo/
rust-nightly-bin /usr/local/share/doc/cargo/LICENSE-APACHE
rust-nightly-bin /usr/local/share/doc/cargo/LICENSE-MIT
rust-nightly-bin /usr/local/share/doc/cargo/LICENSE-THIRD-PARTY
rust-nightly-bin /usr/local/share/doc/cargo/README.md
rust-nightly-bin /usr/local/share/zsh/site-functions/_cargo
```

**Comment by michaelsproul** [comment]
Good idea! I'll mark rust-nightly-bin as conflicting with cargo-nightly-bin and mark cargo-nightly-bin as out of date.

**Comment by SimonSapin** [comment]
There’re not really conflicting, since rust-nightly-bin installs in `/usr/local/` and cargo-nightly-bin in `/usr/`. But it can be confusing that updating cargo-nightly-bin seemingly does nothing because (depending on `$PATH`) the other Cargo takes precedence.

Or do you mean marking them as conflicting to push people to uninstall cargo-nightly-bin?

**Comment by michaelsproul** [comment]
Yeah, just to push people to uninstall `cargo-nightly-bin`.

**Comment by michaelsproul** [comment]
Do you think that's ok?

As release channels are introduced we'll probably get better ways of installing multiple Rust and Cargo versions, but for now I think it's good to keep it simple.

**Comment by SimonSapin** [comment]
Yes, that’s fine. And agreed on multiple Rust channels, see https://github.com/rust-lang/rust/issues/19263 and https://github.com/rust-lang/cargo/issues/967. I’m unsure about multiple versions of Cargo itself though.

**Comment by michaelsproul** [comment]
As of today, cargo-nightly-bin has been deleted!

That should avoid confusion!

https://aur.archlinux.org/packages/cargo-nightly-bin/
