### ISSUE TITLE
"warning: directory permissions differ"

### ISSUE THREAD

**Issue by SimonSapin** [michaelsproul/rust-nightly-archlinux#12]
Re-installing the rust-nightly-bin package, even repeatedly, prints many warnings like this:

```
warning: directory permissions differ on /usr/local/share/doc/rust/html/syntax/diagnostics/registry/
filesystem: 755  package: 775
```

In the filesystem afterwards:

```sh
$ ls -ld /usr/local/share/doc/rust/html/syntax/diagnostics/registry    
drwxr-xr-x 2 root root 4.0K Jan  4 20:03 /usr/local/share/doc/rust/html/syntax/diagnostics/registry/
```

**Comment by michaelsproul** [comment]
Hmm, I saw this error at one stage, but I thought that adding the `chmod` to the `PKGBUILD` fixed it... I've just tried again a few times with both fresh installs and re-installs but haven't been able to reproduce this..? Really weird... :confused:

Have you tried a full uninstall? I suspect this may be why I can't produce the error any more...

**Comment by SimonSapin** [comment]
Ok, uninstalling before re-installing fixes it. (And then still no warning when re-installing without uninstalling first.) It seems that when permissions differ, pacman keeps the old filesystem ones rather than the new package ones. Maybe?

By the way, is it intentional to use `chmod 775` rather than `chmod 755` in the `PKGBUILD`? And are these commands needed at all?

**Comment by michaelsproul** [comment]
Good point! Those permissions hacks were only necessary when I was using `cp` to install the docs. The Rust installer uses `install -d`, which installs directories with 755 permissions.

I'll remove `chmod` for the sake of simplicity, although it will mean more horrendous permissions errors... (your theory about Pacman's behaviour seems to be correct).

**Comment by michaelsproul** [comment]
Thanks for the help!
