### ISSUE TITLE
Why install to /usr again?

### ISSUE THREAD

**Issue by SimonSapin** [michaelsproul/rust-nightly-archlinux#13]
Is https://github.com/rust-lang/rust/issues/16402 not relevant anymore? bc00a983574feeaa234d0afc68b0b90d3d7c2fc0 broke my Servo build (which uses an older Rust snapshot):

```
lib.rs:1:1: 1:1 error: multiple dylib candidates for `std` found
lib.rs:1 /* This Source Code Form is subject to the terms of the Mozilla Public
         ^
lib.rs:1:1: 1:1 note: candidate #1: /usr/lib/libstd-4e7c5e5c.so
lib.rs:1 /* This Source Code Form is subject to the terms of the Mozilla Public
         ^
lib.rs:1:1: 1:1 note: candidate #2: /home/simon/tmp/servo-share/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-4e7c5e5c.so
lib.rs:1 /* This Source Code Form is subject to the terms of the Mozilla Public
         ^
ERROR:rbml::reader: failed to find block with tag 140
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
task 'rustc' panicked at 'explicit panic', /home/larsberg/rust/src/librbml/lib.rs:257

**Comment by michaelsproul** [comment]
Ah, I thought it might have been silently fixed. Sorry for buggering it up!

**Comment by michaelsproul** [comment]
I've reverted the commit and put the `/usr/` stuff on a separate branch.

**Comment by SimonSapin** [comment]
That fixed the issue above, thanks.

It might get fixed when we (Servo) upgrade to a newer Rust version, though. Did you manage to have the AUR package in `/usr` not conflict with another Rust build?

**Comment by michaelsproul** [comment]
Good to hear.

I only really run two versions of Rust, the nightly out of `/usr/local` and a master build out of `~/Rust/`.

**Comment by SimonSapin** [comment]
> I only really run two versions of Rust, the nightly out of `/usr/local` and a master build out of `~/Rust/`.

My question was: did these two not conflict with ``multiple dylib candidates for `std` found`` when you moved nigthly to `/usr`?

**Comment by michaelsproul** [comment]
No, they didn't... I'm fairly sure.

**Comment by michaelsproul** [comment]
You may have noticed some weird behaviour, the package was actually still installing to `/usr/`! Naturally my server didn't remove the commit when it did a `git pull`!

**Comment by SimonSapin** [comment]
I have, but I didn’t complain because it pushed me to try [multirust](https://github.com/brson/multirust) (which I wanted to do anyway). It’s nice!

Unfortunately it looks like this issue is still present in Servo with rustc upgraded to 00b112c45 2015-01-08. It doesn’t affect me anymore since I swtiched to multirust and am not using the AUR package anymore, but it could potentially affect Servo contributors who use Archlinux.

**Comment by michaelsproul** [comment]
Ah yes! I've also been meaning to try multirust!

The package is back in `/usr/local/` so everything should be good for Servo.
