### ISSUE TITLE
Maintainer wanted.

### ISSUE THREAD

**Issue by michaelsproul** [michaelsproul/rust-nightly-archlinux#15]
I've switched to using the wonderful `multirust` in place of this package, so I'm not really testing it any more. I also want to switch my server from Arch to something more stable.

@mikkeloscar, would you be interested in maintaining this?

**Comment by mikkeloscar** [comment]
Hello @michaelsproul I appreciate the consideration but I haven't really used rust for quite a while. I will definitely get back to it at some point, but right now I'm not fit to maintain this. GL finding someone.

**Comment by michaelsproul** [comment]
Ok no worries, thanks for letting me know.
