### ISSUE TITLE
latest nightly tarball does not include doc

### ISSUE THREAD

**Issue by emctoo** [michaelsproul/rust-nightly-archlinux#9]
$ rustc --version
rustc 0.13.0-nightly (7608dbad6 2014-12-31 10:06:21 -0800)

**Comment by emctoo** [comment]
And it fails installation.

**Comment by michaelsproul** [comment]
Sorry, I buggered up the installer in this patch: https://github.com/michaelsproul/rust-nightly-archlinux/commit/8fddc7ea61811c49f629611c5d32175319a61ee4. I should have tested it, but my internet has been pretty dodgy the past few days. I just reverted the change and can confirm that everything works now.

The docs are also fine for me in the new version, let me know if you still have trouble.

**Comment by toshipp** [comment]
it affects me too.
downloaded archive is:
```
 % tar tzf rust-nightly-x86_64-unknown-linux-gnu.tar.gz | grep doc
rust-nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustdoc-4e7c5e5c.so
rust-nightly-x86_64-unknown-linux-gnu/lib/librustdoc-4e7c5e5c.so
rust-nightly-x86_64-unknown-linux-gnu/share/doc/
rust-nightly-x86_64-unknown-linux-gnu/share/doc/rust/
rust-nightly-x86_64-unknown-linux-gnu/share/doc/rust/LICENSE-MIT
rust-nightly-x86_64-unknown-linux-gnu/share/doc/rust/COPYRIGHT
rust-nightly-x86_64-unknown-linux-gnu/share/doc/rust/README.md
rust-nightly-x86_64-unknown-linux-gnu/share/doc/rust/LICENSE-APACHE
rust-nightly-x86_64-unknown-linux-gnu/share/man/man1/rustdoc.1
rust-nightly-x86_64-unknown-linux-gnu/bin/rustdoc
```

**Comment by michaelsproul** [comment]
Ah, you're right. The upstream Rust installers are changing rapidly so I've stripped the PKGBUILD back to the bare minimum for now, and will re-assess in a few days.

The new upstream design is here: https://github.com/rust-lang/rust-packaging, and includes a separate tarball for documentation.

Eventually I'd like to create packages for each of the release channels - nightly, beta and stable.

**Comment by emctoo** [comment]
do remenber including the doc, it helps when offline.

**Comment by michaelsproul** [comment]
Yeah, will do, I also use the offline docs frequently.
